<?php


class HOME_Controller extends MY_Controller
{
	protected $menus = array();

	public function __construct()
	{
		parent::__construct();
//		setting menu
		$this->addMenus([
			[
				'label' => 'HOME',
				'url' => 'home',
			],
			[
				'label' => 'Artikel',
				'sub' => [
					[
						'label' => 'Berita',
						'url' => 'artikel/berita',
					],
				]
			],
			[
				'label' => 'Tentang Kami',
				'sub' => [
					[
						'label' => 'Struktur Organisasi',
						'url' => 'organisasi/struktur',
					],
//						[
//							'label' => 'Struktur Organisasi',
//							'sub' => [
//								[
//									'label' => 'Struktur Organisasi',
//									'url' => 'organisasi/struktur',
//								],
//							],
//						],
				],
			],
		]);
	}

	public function render($view_name, $template = FALSE, $return = FALSE)
	{
		$this->addData('menus', $this->menus);
		return parent::render($view_name, $template, $return); // TODO: Change the autogenerated stub
	}

	/**
	 * @param array $menus
	 */
	public function setMenus($menus)
	{
		$this->menus = $menus;
	}

	/**
	 * @param array $menus
	 */
	public function addMenus($menus)
	{
		$this->menus = array_merge($this->menus, $menus);
	}

}
