<?php


class HOME_Controller extends MY_Controller
{
	protected $menus = array();

	public function __construct()
	{
		parent::__construct();
//		setting menu
		$this->addMenus([
			[
				'label' => 'HOME',
				'url' => 'home',
			],
			[
				'label' => 'Artikel',
				'sub' => [
					[
						'label' => 'Berita',
						'url' => 'artikel/berita',
					],
				]
			],
			[
				'label' => 'galeri',
				'url' => 'home',
			],
			[
				'label' => 'Layanan',
				'sub' => [
					[
						'label' => 'Peraturan',
						'url' => 'layanan/peraturan',
					],
					[
						'label' => 'Panduan',
						'url' => 'layanan/panduan',
					],
					[
						'label' => 'Sosialisasi',
						'url' => 'layanan/sosialisasi',
					],
					[
						'label' => 'Laporan Meninggal Dunia',
						'url' => 'layanan/sosialisasi',
					],
					[
						'label' => 'Cetak e-spt',
						'url' => 'layanan/e_spt',
					],
					[
						'label' => 'Update Data Diri',
						'url' => 'layanan/e_spt',
					],
					[
						'label' => 'Simulasi Manfaat Pensiun',
						'url' => 'layanan/simulasi',
					],

					[
						'label' => 'Simulasi Manfaat Pensiun',
						'url' => 'layanan/simulasi',
					],

					[
						'label' => 'Cetak Kartu',
						'url' => 'layanan/cetak',
					],

				]
			],
			[
				'label' => 'Tentang Kami',
				'sub' => [
					[
						'label' => 'Struktur Organisasi',
						'url' => 'organisasi/struktur',
					],
					[
						'label' => 'Visi Misi',
						'url' => 'tentang/visi_misi',
					],
					[
						'label' => 'Motto',
						'url' => 'tentang/motto',
					],
				],
			],
		]);
	}

	public function render($view_name, $template = FALSE, $return = FALSE)
	{
		$this->addData('menus', $this->menus);
		return parent::render($view_name, $template, $return); // TODO: Change the autogenerated stub
	}

	/**
	 * @param array $menus
	 */
	public function setMenus($menus)
	{
		$this->menus = $menus;
	}

	/**
	 * @param array $menus
	 */
	public function addMenus($menus)
	{
		$this->menus = array_merge($this->menus, $menus);
	}

}
